# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dbc74dfdf392a9ffa43d65c2a6e8f8bd4411db621d288835beefe2adc165bd74bb1bd825430ebc64095f2c7f0ce9d0a33b1829c2650825a272e65e5146cf3d3

test:
  secret_key_base: 21bc9f261bdf63248d22300db5d8b84b692bc440968decc597b5dfab2ecfa1017400cb20511decbfe9edc3e1086b241442f43ee2adff852ae337d7994449f70c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
